const WINNER_TOTAL_COUNT = 1006;
const ROUND_WISE_TICKETS_COUNT = 5000;
const TRANSACTION_TIMEOUT_SECONDS = 5 * 60; // 5 minutes in seconds
const TRANSACTION_TIMEOUT_MINUTES = 30; // 30 minutes in minutes

module.exports = {
    WINNER_TOTAL_COUNT,
    ROUND_WISE_TICKETS_COUNT,
    TRANSACTION_TIMEOUT_SECONDS,
    TRANSACTION_TIMEOUT_MINUTES
}